#! /usr/bin/dash

ext_dsp=$(cat /sys/class/drm/card0-HDMI-A-2/status)

### Wallpapers ###

LAPTOP_WALL="$HOME/.wallpaper/gruvboxtux.png"
HDMI2_WALL="$HOME/.wallpaper/rain-skyline.jpg"

LAPTOP_BAR="laptop"
HDMI2_BAR="main"

#######

setxkbmap dvorak
xmodmap ~/.xmodmap

#######

sxhkd &
dunst &
#polybar $LAPTOP_BAR & >/dev/null
~/.config/polybar/launch.sh&
#######
##########

# bspc config border_radius        10
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          40
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#bf616a"
bspc config focused_border_color	"#d3869b"
bspc config presel_feedback_color	"#5e81ac"

##########
#######
if [ "$ext_dsp" = "connected" ]; then
  xrandr --output eDP-1 --auto --output HDMI-2 --left-of eDP-1 --auto
  bspc monitor eDP-1  -d 1 2 3 4 5 6
  bspc monitor HDMI-2 -d 1 2 3 4 5 6
  #polybar $HDMI2_BAR &
  xwallpaper --output eDP-1  --zoom  $LAPTOP_WALL \
             --output HDMI-2 --focus  $HDMI2_WALL
else
  xrandr --output eDP-1 --auto
  bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9
  xwallpaper --output eDP-1  --zoom  $LAPTOP_WALL
fi
# vim:ft=sh
