#! /usr/bin/dash

ext_dsp=$(cat /sys/class/drm/card0-HDMI-A-2/status)

### Wallpapers ###

LAPTOP_WALL="$HOME/.wallpaper/Calder-Moore_Factory-comped.jpg"
HDMI2_WALL="$HOME/.wallpaper/rocket-sunset_3440x1440.png"

LAPTOP_BAR="laptop"
HDMI2_BAR="main"

#######

setxkbmap dvorak
xmodmap ~/.xmodmap

#######

sxhkd &
dunst &
polybar $LAPTOP_BAR & >/dev/null
#######

#bspc config border_width 2
#bspc config top_padding      10
#bspc config bottom_padding   44
#bspc config left_padding     17
#bspc config right_padding    17

#####
if [ "$ext_dsp" = "connected" ]; then
  bspc monitor eDP-1  -d 1 2 3 4 5 6
  bspc monitor HDMI-2 -d 1 2 3 4 5 6
  polybar $HDMI2_BAR &
  xwallpaper --output eDP-1  --zoom  $LAPTOP_WALL \
             --output HDMI-2 --center  $HDMI2_WALL
else
  bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9
  xwallpaper --output eDP-1  --zoom  $LAPTOP_WALL
fi
# vim:ft=sh
