#!/bin/dash

sxhkd &

if [ $(cat /sys/class/drm/card0-HDMI-A-2/status) = "connected" ]; then
  bspc monitor eDP-1  -d 1 2 3 4 5 6
  bspc monitor HDMI-2 -d 1 2 3 4 5 6
  polybar main &
else
  bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9
fi

xmodmap ~/.xmodmap &

bspc config window_gap            2
bspc config split_ratio           0.60
bspc config border_width          3

bspc config gapless_monocle       true
bspc config borderless_monocle    true

bspc config active_border_color  '#88509B' # selected window, inactive monitor
bspc config normal_border_color  '#75756E' # unselected window
bspc config focused_border_color '#BC5420' # selected window, active monitor

polybar main-laptop &

xwallpaper --output eDP-1  --zoom  ~/.wallpaper/calvinhobbes.png \
           --output HDMI-2 --zoom  ~/.wallpaper/Vladimir-Motsar_1.jpg

dunst &
# vi: ft=sh
