#!/usr/bin/env zsh
#####################
##     Polybar     ##
#####################
polybar main-laptop &;
dunst &
sxhkd &

if [[ $(cat /sys/class/drm/card0-HDMI-A-2/status) == "connected" ]] {

  echo "HDMI-2 connected";
  xrandr --output HDMI-2 --mode 1920x1200 --primary --right-of eDP-1;
  polybar main &;
  bspc monitor HDMI-2  -d 7 8 9 10
  bspc monitor eDP-1 -d 1 2 3 4 5 6

} else {

  echo "HDMI-2 not connected";
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

}

#####################
##      BSPWM      ##
#####################
bspc config border_width   2
bspc config window_gap     4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#'#0A0A2B'
#'#B77DD7'
#'#A26FBF'
bspc config active_border_color  '#F55050'
bspc config normal_border_color  '#75756e'
bspc config focused_border_color '#A26FBF'


xmodmap /home/alex/.xmodmap &
feh --bg-fill \
  /home/alex/.wallpaper/Eytan-Zana_Storms-coming.jpg \
  /home/alex/.wallpaper/Eytan-Zana_Glacier.jpg
